- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: "duplicate"
  color: "cfd8d7"
  description: "This issue or pull request already exists"
- name: "enhancement"
  color: "a22eef"
- name: "chore"
  color: "f0f8ff"
  description: "Miscellaneous tasks not related to function"
- name: "major"
  color: "dc143c"
  description: "major version when you make incompatible API changes"
- name: "minor"
  color: "dc143c"
  description: "minor version when you add functionality in a backwards compatible manner"
- name: "patch"
  color: "dc143c"
  description: "patch version when you make backwards compatible bug fixes"